-- return {
-- 	"quarto-dev/quarto-nvim",
-- 	dev = false,
-- 	dependencies = {
-- 		{
-- 			"jmbuhr/otter.nvim",
-- 			dev = false,
-- 			config = function()
-- 				require("otter").setup({
-- 					lsp = {
-- 						hover = {
-- 							border = { "╭", "─", "╮", "│", "╯", "─", "╰", "│" },
-- 						},
-- 					},
-- 				})
-- 			end,
-- 		},
-- 	},
-- 	config = function()
-- 		require("quarto").setup({
-- 			closePreviewOnExit = true,
-- 			lspFeatures = {
-- 				enabled = true,
-- 				chunks = "curly",
-- 				languages = { "r", "python", "julia", "bash", "lua", "html" },
-- 				diagnostics = {
-- 					enabled = true,
-- 					triggers = { "BufWritePost" },
-- 				},
-- 				completion = {
-- 					enabled = true,
-- 				},
-- 				keymap = {
-- 					hover = "K",
-- 					definition = "gd",
-- 					rename = "<leader>lR",
-- 					references = "gr",
-- 				},
-- 			},
-- 		})
-- 	end,
-- }
return {}
