return {}

-- return {
-- 	"bluz71/vim-moonfly-colors",
-- 	name = "moonfly",
-- 	lazy = false,
-- 	priority = 1000,
-- 	config = function()
-- 		vim.cmd("colorscheme moonfly")
-- 		vim.g.moonflyTransparent = true
-- 	end,
-- }

-- return {
-- 	"luisiacc/gruvbox-baby",
-- 	config = function()
-- 		vim.g.gruvbox_baby_transparent = true
-- 		vim.cmd("colorscheme gruvbox-baby")
-- 		vim.api.nvim_set_hl(0, "Normal", { bg = "none" })
-- 		vim.api.nvim_set_hl(0, "NormalFloat", { bg = "none" })
-- 		vim.api.nvim_set_hl(0, "FloatBorder", { bg = "none" })
-- 		vim.api.nvim_set_hl(0, "SignColumn", { bg = "none" })
-- 		-- vim.api.nvim_set_hl(0, "LineNr", { bg = "none" })
-- 	end,
-- }

-- return {
-- 	"blazkowolf/gruber-darker.nvim",
-- 	config = function()
-- 		vim.cmd.colorscheme("gruber-darker")
-- 		vim.api.nvim_set_hl(0, "NormalFloat", { bg = "none" })
-- 	end,
-- }

-- return {
-- 	"rose-pine/neovim",
-- 	config = function()
-- 		vim.cmd("colorscheme rose-pine-main")
-- 		vim.api.nvim_set_hl(0, "Normal", { bg = "none" })
-- 		vim.api.nvim_set_hl(0, "NormalFloat", { bg = "none" })
-- 		vim.api.nvim_set_hl(0, "FloatBorder", { bg = "none" })
-- 		vim.api.nvim_set_hl(0, "NormalNC", { bg = "none" })
-- 	end,
-- }

-- return {
-- 	"rebelot/kanagawa.nvim",
-- 	-- Default options:
-- 	config = function()
-- 		require("kanagawa").setup({})
-- 		vim.cmd("colorscheme kanagawa-dragon")
-- 		vim.api.nvim_set_hl(0, "Normal", { bg = "none" })
-- 		vim.api.nvim_set_hl(0, "NormalFloat", { bg = "none" })
-- 		vim.api.nvim_set_hl(0, "FloatBorder", { bg = "none" })
-- 		vim.api.nvim_set_hl(0, "NormalNC", { bg = "none" })
-- 		vim.api.nvim_set_hl(0, "SignColumn", { bg = "none" })
-- 		vim.api.nvim_set_hl(0, "LineNr", { bg = "none" })
-- 	end,
-- }

-- return {
-- 	"ellisonleao/gruvbox.nvim",
-- 	priority = 1000,
-- 	config = function()
-- 		require("gruvbox").setup({
-- 			transparent_mode = true,
-- 		})
-- 		vim.o.background = "dark"
-- 		vim.cmd.colorscheme("gruvbox")
-- 	end,
-- }

-- return {
-- 	"catppuccin/nvim",
-- 	name = "catppuccin",
-- 	priority = 1000,
-- 	config = function()
-- 		require("catppuccin").setup({
-- 			transparent_background = true,
-- 		})
-- 		vim.cmd.colorscheme("catppuccin")
-- 	end,
-- }
